Rewrite ocserv.init

diff --git a/debian/ocserv.init b/debian/ocserv.init
--- a/debian/ocserv.init
+++ b/debian/ocserv.init
@@ -1,18 +1,104 @@
-#!/lib/init/init-d-script
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides:          ocserv
-# Required-Start:    $remote_fs $syslog dbus
-# Required-Stop:     $remote_fs $syslog dbus
-# Default-Start:     2 3 4 5
-# Default-Stop:      0 1 6
-# Short-Description: OpenConnect SSL VPN server
-# Description:       Debian init script to start the ocserv daemon.
+# Provides:		ocserv
+# Required-Start:	$remote_fs $syslog dbus
+# Required-Stop:	$remote_fs $syslog dbus
+# Default-Start:	2 3 4 5
+# Default-Stop:		0 1 6
+# Short-Description:	OpenConnect SSL VPN server
+# Description:          secure, small, fast and configurable OpenConnect SSL VPN server
 ### END INIT INFO
+set -e
+
+NAME=ocserv
 DAEMON=/usr/sbin/ocserv
 DESC="OpenConnect SSL VPN server"
-PIDFILE=/var/run/ocserv.pid
-DAEMON_ARGS="--pid-file $PIDFILE --config /etc/ocserv/ocserv.conf"
+PIDFILE=/var/run/${NAME}.pid
+DAEMON_ARGS="--pid-file $PIDFILE --config /etc/${NAME}/${NAME}.conf"
 
-# Lintian does not yet handle init-d-script scripts, so name the common
-# init script options to bypass the error check.
-NOT_USED="start stop restart force-reload status"
+test -x $DAEMON || exit 0
+
+umask 022
+
+. /lib/lsb/init-functions
+
+# Are we running from init?
+run_by_init() {
+    ([ "$previous" ] && [ "$runlevel" ]) || [ "$runlevel" = S ]
+}
+
+export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
+
+case "$1" in
+  start)
+	log_daemon_msg "Starting $DESC" "$NAME" || true
+	if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS ; then
+	    log_end_msg 0 || true
+	else
+	    log_end_msg 1 || true
+	fi
+	;;
+  stop)
+	log_daemon_msg "Stopping $DESC" "$NAME" || true
+	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
+	    log_end_msg 0 || true
+	else
+	    log_end_msg 1 || true
+	fi
+	;;
+
+  reload|force-reload)
+	log_daemon_msg "Reloading $DESC" "$NAME" || true
+	if start-stop-daemon --stop --signal 1 --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON; then
+	    log_end_msg 0 || true
+	else
+	    log_end_msg 1 || true
+	fi
+	;;
+
+  restart)
+	log_daemon_msg "Restarting $DESC" "$NAME" || true
+	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
+	if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS; then
+	    log_end_msg 0 || true
+	else
+	    log_end_msg 1 || true
+	fi
+	;;
+
+  try-restart)
+	log_daemon_msg "Restarting $DESC" "$NAME" || true
+	RET=0
+	start-stop-daemon --stop --quiet --retry 30 --pidfile $PIDFILE || RET="$?"
+	case $RET in
+	    0)
+		# old daemon stopped
+		if start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_ARGS; then
+		    log_end_msg 0 || true
+		else
+		    log_end_msg 1 || true
+		fi
+		;;
+	    1)
+		# daemon not running
+		log_progress_msg "(not running)" || true
+		log_end_msg 0 || true
+		;;
+	    *)
+		# failed to stop
+		log_progress_msg "(failed to stop)" || true
+		log_end_msg 1 || true
+		;;
+	esac
+	;;
+
+  status)
+	status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
+	;;
+
+  *)
+	log_action_msg "Usage: /etc/init.d/$NAME {start|stop|reload|force-reload|restart|try-restart|status}" || true
+	exit 1
+esac
+
+exit 0
